//! Dialog turn tracking — one user↔agent round-trip.
//!
//! A `DialogTurn` captures the full lifecycle of a single interaction:
//! from the moment the user sends a message until the agent produces its
//! final response (or the turn is cancelled / errors out).
//!
//! ## Why this exists
//!
//! Without turn tracking:
//! - Cancel means "kill the whole session" — no way to cancel just the current LLM call
//! - Rollback (e.g. git undo) has no reference point for "what changed this turn"
//! - Frontend cannot distinguish "session idle" from "turn N completed, session still open"
//! - Retry cannot identify the exact turn to re-run
//!
//! ## Usage
//!
//! The `UnifiedMessageProcessor` creates a `DialogTurn` at the top of `process()`,
//! stores it in `AgentSession::active_turn`, and finalizes it (Completed / Cancelled /
//! Failed) before returning.  The `turn_id` is included in the `agent:complete` broadcast
//! so the frontend can correlate events.

use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::Arc;
use std::time::{Duration, Instant};

use serde::{Deserialize, Serialize};

// ============================================
// DialogTurnState
// ============================================

/// Lifecycle state of a single dialog turn.
///
/// Transitions: `Running → Completed | Cancelled | Failed`
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum DialogTurnState {
    /// Turn is actively executing.
    Running,
    /// Turn completed successfully.
    Completed,
    /// Turn was cancelled by the user (via `cancel_flag`).
    Cancelled,
    /// Turn terminated with an error.
    Failed,
}

// ============================================
// TurnStats
// ============================================

/// Token usage and tool-call statistics for a completed turn.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TurnStats {
    /// Tokens in the prompt sent to the LLM.
    pub prompt_tokens: i64,
    /// Tokens generated by the LLM.
    pub completion_tokens: i64,
    /// Total tokens (prompt + completion).
    pub total_tokens: i64,
    /// Context window tokens at the time of the call.
    pub context_tokens: i64,
    /// Number of tool calls made during this turn.
    pub tool_calls_count: u32,
    /// Wall-clock duration of the turn.
    #[serde(skip)]
    pub duration: Option<Duration>,
}

// ============================================
// DialogTurn
// ============================================

/// A single user↔agent interaction round-trip.
///
/// Created at the start of `process()`, finalized before it returns.
/// Stored as `AgentSession::active_turn` while the turn is executing;
/// cleared (set to `None`) once finalized.
#[derive(Debug)]
pub struct DialogTurn {
    /// Stable UUID for this turn — used for cancel targeting and frontend correlation.
    pub turn_id: String,
    /// Current lifecycle state of the turn.
    pub state: DialogTurnState,
    /// The raw user message that started this turn.
    pub user_input: String,
    /// Statistics collected during the turn (populated on completion).
    pub stats: TurnStats,
    /// Wall-clock start time (not serialized — use `stats.duration` instead).
    pub started_at: Instant,
    /// The cancellation flag shared with the processor and `AgentSession`.
    ///
    /// Holding a reference here lets callers do `turn.cancel()` directly
    /// without going through `AgentSession`.
    pub cancel_flag: Arc<AtomicBool>,
}

impl DialogTurn {
    /// Create a new running turn.
    pub fn new(user_input: String, cancel_flag: Arc<AtomicBool>) -> Self {
        Self {
            turn_id: uuid::Uuid::new_v4().to_string(),
            state: DialogTurnState::Running,
            user_input,
            stats: TurnStats::default(),
            started_at: Instant::now(),
            cancel_flag,
        }
    }

    /// Signal cancellation via the shared flag.
    ///
    /// This does not change `state` immediately — the processor will call
    /// `finalize(DialogTurnState::Cancelled, ...)` once it observes the flag.
    pub fn cancel(&self) {
        self.cancel_flag.store(true, Ordering::SeqCst);
    }

    /// Mark the turn as finished and record statistics.
    ///
    /// Call this exactly once, at the end of `process()`.
    pub fn finalize(&mut self, state: DialogTurnState, stats: TurnStats) {
        self.state = state;
        self.stats = TurnStats {
            duration: Some(self.started_at.elapsed()),
            ..stats
        };
    }

    /// Whether this turn has finished (in any terminal state).
    pub fn is_finished(&self) -> bool {
        self.state != DialogTurnState::Running
    }

    /// Duration so far (even for a running turn).
    pub fn elapsed(&self) -> Duration {
        self.started_at.elapsed()
    }
}
