//! Dialog turn tracking — one user↔agent round-trip.
//!
//! A `DialogTurn` captures the full lifecycle of a single interaction:
//! from the moment the user sends a message until the agent produces its
//! final response (or the turn is cancelled / errors out).
//!
//! ## Why this exists
//!
//! Without turn tracking:
//! - Cancel means "kill the whole session" — no way to cancel just the current LLM call
//! - Rollback (e.g. git undo) has no reference point for "what changed this turn"
//! - Frontend cannot distinguish "session idle" from "turn N completed, session still open"
//! - Retry cannot identify the exact turn to re-run
//!
//! ## Usage
//!
//! The `UnifiedMessageProcessor` creates a `DialogTurn` at the top of `process()`,
//! stores it in `AgentSession::active_turn`, and finalizes it (Completed / Cancelled /
//! Failed) before returning.  The `turn_id` is included in the `agent:complete` broadcast
//! so the frontend can correlate events.

use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::Arc;
use std::time::{Duration, Instant};

use serde::{Deserialize, Serialize};

// ============================================
// DialogTurnState
// ============================================

/// Lifecycle state of a single dialog turn.
///
/// Transitions: `Running → Completed | Cancelled | Failed`
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum DialogTurnState {
    /// Turn is actively executing.
    Running,
    /// Turn completed successfully.
    Completed,
    /// Turn was cancelled by the user (via `cancel_flag`).
    Cancelled,
    /// Turn terminated with an error.
    Failed,
}

// ============================================
// TurnStats
// ============================================

/// Token usage and tool-call statistics for a completed turn.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TurnStats {
    /// Tokens in the prompt sent to the LLM.
    pub prompt_tokens: i64,
    /// Tokens generated by the LLM.
    pub completion_tokens: i64,
    /// Total tokens (prompt + completion).
    pub total_tokens: i64,
    /// Context window tokens at the time of the call.
    pub context_tokens: i64,
    /// Number of tool calls made during this turn.
    pub tool_calls_count: u32,
    /// Wall-clock duration of the turn.
    #[serde(skip)]
    pub duration: Option<Duration>,
}

// ============================================
// DialogTurn
// ============================================

/// A single user↔agent interaction round-trip.
///
/// Created at the start of `process()`, finalized before it returns.
/// Stored as `AgentSession::active_turn` while the turn is executing;
/// cleared (set to `None`) once finalized.
#[derive(Debug)]
pub struct DialogTurn {
    /// Stable UUID for this turn — used for cancel targeting and frontend correlation.
    pub turn_id: String,
    /// Current lifecycle state of the turn.
    pub state: DialogTurnState,
    /// The raw user message that started this turn.
    pub user_input: String,
    /// Statistics collected during the turn (populated on completion).
    pub stats: TurnStats,
    /// Wall-clock start time (not serialized — use `stats.duration` instead).
    pub started_at: Instant,
    /// The cancellation flag shared with the processor and `AgentSession`.
    ///
    /// Holding a reference here lets callers do `turn.cancel()` directly
    /// without going through `AgentSession`.
    pub cancel_flag: Arc<AtomicBool>,
}

impl DialogTurn {
    /// Create a new running turn.
    pub fn new(user_input: String, cancel_flag: Arc<AtomicBool>) -> Self {
        Self {
            turn_id: uuid::Uuid::new_v4().to_string(),
            state: DialogTurnState::Running,
            user_input,
            stats: TurnStats::default(),
            started_at: Instant::now(),
            cancel_flag,
        }
    }

    /// Signal cancellation via the shared flag.
    ///
    /// This does not change `state` immediately — the processor will call
    /// `finalize(DialogTurnState::Cancelled, ...)` once it observes the flag.
    pub fn cancel(&self) {
        self.cancel_flag.store(true, Ordering::SeqCst);
    }

    /// Mark the turn as finished and record statistics.
    ///
    /// Call this exactly once, at the end of `process()`.
    pub fn finalize(&mut self, state: DialogTurnState, stats: TurnStats) {
        self.state = state;
        self.stats = TurnStats {
            duration: Some(self.started_at.elapsed()),
            ..stats
        };
    }

    /// Whether this turn has finished (in any terminal state).
    pub fn is_finished(&self) -> bool {
        self.state != DialogTurnState::Running
    }

    /// Duration so far (even for a running turn).
    pub fn elapsed(&self) -> Duration {
        self.started_at.elapsed()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn make_turn(input: &str) -> DialogTurn {
        DialogTurn::new(input.to_string(), Arc::new(AtomicBool::new(false)))
    }

    // -----------------------------------------------------------------------
    // Initial state
    // -----------------------------------------------------------------------

    #[test]
    fn new_turn_starts_in_running_state() {
        let turn = make_turn("hello");
        assert_eq!(turn.state, DialogTurnState::Running);
    }

    #[test]
    fn new_turn_preserves_user_input() {
        let turn = make_turn("my message");
        assert_eq!(turn.user_input, "my message");
    }

    #[test]
    fn new_turn_is_not_finished() {
        let turn = make_turn("hello");
        assert!(!turn.is_finished());
    }

    #[test]
    fn new_turn_has_zeroed_stats() {
        let turn = make_turn("hello");
        assert_eq!(turn.stats.prompt_tokens, 0);
        assert_eq!(turn.stats.completion_tokens, 0);
        assert_eq!(turn.stats.tool_calls_count, 0);
    }

    #[test]
    fn new_turn_has_unique_turn_id() {
        let a = make_turn("a");
        let b = make_turn("b");
        assert_ne!(a.turn_id, b.turn_id, "turn_ids must be unique per turn");
    }

    // -----------------------------------------------------------------------
    // cancel() — sets atomic flag without changing state
    // -----------------------------------------------------------------------

    #[test]
    fn cancel_sets_flag_without_changing_state() {
        let turn = make_turn("hello");
        turn.cancel();
        // The cancel flag is now set …
        assert!(turn.cancel_flag.load(Ordering::SeqCst));
        // … but state is still Running until finalize() is called
        assert_eq!(turn.state, DialogTurnState::Running);
        assert!(!turn.is_finished());
    }

    // -----------------------------------------------------------------------
    // finalize() — state transitions: Running → terminal
    // -----------------------------------------------------------------------

    #[test]
    fn finalize_completed_transitions_state() {
        let mut turn = make_turn("hello");
        let stats = TurnStats {
            prompt_tokens: 10,
            completion_tokens: 20,
            ..Default::default()
        };
        turn.finalize(DialogTurnState::Completed, stats);
        assert_eq!(turn.state, DialogTurnState::Completed);
        assert!(turn.is_finished());
    }

    #[test]
    fn finalize_cancelled_transitions_state() {
        let mut turn = make_turn("hello");
        turn.finalize(DialogTurnState::Cancelled, TurnStats::default());
        assert_eq!(turn.state, DialogTurnState::Cancelled);
        assert!(turn.is_finished());
    }

    #[test]
    fn finalize_failed_transitions_state() {
        let mut turn = make_turn("hello");
        turn.finalize(DialogTurnState::Failed, TurnStats::default());
        assert_eq!(turn.state, DialogTurnState::Failed);
        assert!(turn.is_finished());
    }

    #[test]
    fn finalize_records_token_stats() {
        let mut turn = make_turn("hello");
        let stats = TurnStats {
            prompt_tokens: 50,
            completion_tokens: 75,
            total_tokens: 125,
            tool_calls_count: 3,
            ..Default::default()
        };
        turn.finalize(DialogTurnState::Completed, stats);
        assert_eq!(turn.stats.prompt_tokens, 50);
        assert_eq!(turn.stats.completion_tokens, 75);
        assert_eq!(turn.stats.total_tokens, 125);
        assert_eq!(turn.stats.tool_calls_count, 3);
    }

    #[test]
    fn finalize_sets_duration_in_stats() {
        let mut turn = make_turn("hello");
        turn.finalize(DialogTurnState::Completed, TurnStats::default());
        assert!(
            turn.stats.duration.is_some(),
            "finalize() must populate stats.duration"
        );
    }

    // -----------------------------------------------------------------------
    // DialogTurnState — is_finished boundaries
    // -----------------------------------------------------------------------

    #[test]
    fn only_running_is_not_finished() {
        let running_turn = make_turn("hello");
        assert!(
            !running_turn.is_finished(),
            "Running turn must not be finished"
        );
        // All terminal variants must satisfy is_finished via `!= Running` logic
        let terminal = [
            DialogTurnState::Completed,
            DialogTurnState::Cancelled,
            DialogTurnState::Failed,
        ];
        for state in terminal {
            let mut turn = make_turn("hello");
            turn.finalize(state, TurnStats::default());
            assert!(turn.is_finished(), "{:?} turn must be finished", state);
        }
    }

    // -----------------------------------------------------------------------
    // DialogTurnState serde round-trip
    // -----------------------------------------------------------------------

    #[test]
    fn turn_state_serializes_to_snake_case() {
        assert_eq!(
            serde_json::to_string(&DialogTurnState::Running).unwrap(),
            "\"running\""
        );
        assert_eq!(
            serde_json::to_string(&DialogTurnState::Completed).unwrap(),
            "\"completed\""
        );
        assert_eq!(
            serde_json::to_string(&DialogTurnState::Cancelled).unwrap(),
            "\"cancelled\""
        );
        assert_eq!(
            serde_json::to_string(&DialogTurnState::Failed).unwrap(),
            "\"failed\""
        );
    }

    #[test]
    fn turn_state_deserializes_from_snake_case() {
        let states = ["running", "completed", "cancelled", "failed"];
        let expected = [
            DialogTurnState::Running,
            DialogTurnState::Completed,
            DialogTurnState::Cancelled,
            DialogTurnState::Failed,
        ];
        for (s, expected) in states.iter().zip(expected.iter()) {
            let json = format!("\"{}\"", s);
            let got: DialogTurnState = serde_json::from_str(&json).unwrap();
            assert_eq!(got, *expected, "Deserializing {:?}", s);
        }
    }
}
