import type { StatusPreset } from "../../types";

export const specialFileToolPresets: Record<string, StatusPreset[]> = {
  edit_file: [
    {
      key: "completed",
      label: "Completed",
      status: "completed",
    },
    {
      key: "streaming",
      label: "Streaming",
      status: "running",
      resultPatch: { success: undefined, diff: undefined },
      argsPatch: {
        streamContent: [
          "import { useState, useCallback, useEffect, useRef, useMemo } from 'react';",
          "import type { EventEmitter } from 'events';",
          "import type { DebugConfig, LogEntry, TransportOptions } from './types';",
          "",
          "// ── Constants ──",
          "",
          "const MAX_BUFFER_SIZE = 4096;",
          "const FLUSH_INTERVAL_MS = 250;",
          "const DEFAULT_LOG_LEVEL = 'info' as const;",
          "",
          "type LogLevel = 'trace' | 'debug' | 'info' | 'warn' | 'error' | 'fatal';",
          "",
          "const LOG_LEVEL_PRIORITY: Record<LogLevel, number> = {",
          "  trace: 0,",
          "  debug: 1,",
          "  info: 2,",
          "  warn: 3,",
          "  error: 4,",
          "  fatal: 5,",
          "};",
          "",
          "// ── Configuration ──",
          "",
          "export interface LoggerOptions {",
          "  enabled: boolean;",
          "  verbose: boolean;",
          "  minLevel: LogLevel;",
          "  maxEntries: number;",
          "  persistToStorage: boolean;",
          "  transport?: TransportOptions;",
          "  formatTimestamp?: (date: Date) => string;",
          "  onFlush?: (entries: LogEntry[]) => void;",
          "}",
          "",
          "export const DEFAULT_LOGGER_CONFIG: LoggerOptions = {",
          "  enabled: true,",
          "  verbose: false,",
          "  minLevel: DEFAULT_LOG_LEVEL,",
          "  maxEntries: 2000,",
          "  persistToStorage: false,",
          "};",
          "",
          "// ── Formatting ──",
          "",
          "function formatEntry(level: LogLevel, message: string, timestamp: Date): string {",
          "  const ts = timestamp.toISOString();",
          "  const prefix = `[${level.toUpperCase().padEnd(5)}]`;",
          "  return `${prefix} ${ts} ${message}`;",
          "}",
          "",
          "function shouldLog(level: LogLevel, minLevel: LogLevel): boolean {",
          "  return LOG_LEVEL_PRIORITY[level] >= LOG_LEVEL_PRIORITY[minLevel];",
          "}",
          "",
          "// ── Buffer Management ──",
          "",
          "interface BufferState {",
          "  entries: LogEntry[];",
          "  pendingFlush: boolean;",
          "  lastFlushAt: number;",
          "}",
          "",
          "function createBuffer(): BufferState {",
          "  return { entries: [], pendingFlush: false, lastFlushAt: Date.now() };",
          "}",
          "",
          "function appendToBuffer(buffer: BufferState, entry: LogEntry): BufferState {",
          "  const entries = [...buffer.entries, entry];",
          "  if (entries.length > MAX_BUFFER_SIZE) {",
          "    return { ...buffer, entries: entries.slice(-MAX_BUFFER_SIZE), pendingFlush: true };",
          "  }",
          "  return { ...buffer, entries, pendingFlush: entries.length >= MAX_BUFFER_SIZE / 2 };",
          "}",
          "",
          "// ── Hook ──",
          "",
          "export function useStructuredLogger(config: Partial<LoggerOptions> = {}) {",
          "  const options = useMemo(",
          "    () => ({ ...DEFAULT_LOGGER_CONFIG, ...config }),",
          "    [config]",
          "  );",
          "  const bufferRef = useRef<BufferState>(createBuffer());",
          "  const timerRef = useRef<ReturnType<typeof setInterval>>();",
          "",
          "  const flush = useCallback(() => {",
          "    const buffer = bufferRef.current;",
          "    if (buffer.entries.length === 0) return;",
          "    options.onFlush?.(buffer.entries);",
          "    if (options.persistToStorage) {",
          "      try {",
          "        const serialized = JSON.stringify(buffer.entries.slice(-options.maxEntries));",
          "        localStorage.setItem('structured-log', serialized);",
          "      } catch { /* storage full */ }",
          "    }",
          "    bufferRef.current = createBuffer();",
          "  }, [options]);",
          "",
          "  const log = useCallback(",
          "    (message: string, level: LogLevel = 'info', meta?: Record<string, unknown>) => {",
          "      if (!options.enabled) return;",
          "      if (!shouldLog(level, options.minLevel)) return;",
          "      const timestamp = new Date();",
          "      const entry: LogEntry = {",
          "        level,",
          "        message: formatEntry(level, message, timestamp),",
          "        raw: message,",
          "        timestamp: timestamp.getTime(),",
          "        meta,",
          "      };",
          "      bufferRef.current = appendToBuffer(bufferRef.current, entry);",
          "      if (level === 'fatal' || level === 'error') flush();",
          "    },",
          "    [options.enabled, options.minLevel, flush]",
          "  );",
          "",
          "  const clear = useCallback(() => {",
          "    bufferRef.current = createBuffer();",
          "    if (options.persistToStorage) localStorage.removeItem('structured-log');",
          "  }, [options.persistToStorage]);",
          "",
          "  useEffect(() => {",
          "    timerRef.current = setInterval(flush, FLUSH_INTERVAL_MS);",
          "    return () => {",
          "      clearInterval(timerRef.current);",
          "      flush();",
          "    };",
          "  }, [flush]);",
          "",
          "  useEffect(() => {",
          "    if (!options.persistToStorage) return;",
          "    try {",
          "      const saved = localStorage.getItem('structured-log');",
          "      if (saved) {",
          "        const parsed: LogEntry[] = JSON.parse(saved);",
          "        bufferRef.current = { ...bufferRef.current, entries: parsed };",
          "      }",
          "    } catch { /* corrupted */ }",
          "  }, [options.persistToStorage]);",
          "",
          "  return { log, flush, clear, getEntries: () => bufferRef.current.entries };",
          "}",
        ].join("\n"),
      },
    },
    {
      key: "streaming-empty",
      label: "Streaming (no content yet)",
      status: "running",
      resultPatch: { success: undefined, diff: undefined },
      argsPatch: { streamContent: undefined, new_string: undefined },
    },
    {
      key: "failed",
      label: "Failed",
      status: "failed",
    },
  ],
  apply_patch: [
    {
      key: "completed",
      label: "Completed",
      status: "completed",
    },
    {
      key: "streaming",
      label: "Streaming",
      status: "running",
      resultPatch: { success: undefined, content: undefined },
      argsPatch: {
        patch_text: undefined,
        streamContent: [
          "*** Begin Patch",
          "*** Add File: src/utils/dateFormat.ts",
          "+import { padStart } from './strings';",
          "+",
          "+export function formatDate(date: Date): string {",
          "+  return date.toISOString().split('T')[0];",
          "+}",
          "+",
          "+export function formatRelative(date: Date): string {",
          "+  const diff = Date.now() - date.getTime();",
          "+  const seconds = Math.floor(diff / 1000);",
          "+  if (seconds < 60) return 'just now';",
          "+  const minutes = Math.floor(seconds / 60);",
          "+  if (minutes < 60) return `${minutes}m ago`;",
          "+  const hours = Math.floor(minutes / 60);",
          "+  return `${hours}h ago`;",
          "+}",
          "*** Modify File: src/config/settings.ts",
          " // Application settings",
          "-const DEBUG = false;",
          "+const DEBUG = true;",
          " ",
          "-const LOG_LEVEL = 'warn';",
          "+const LOG_LEVEL = 'debug';",
          " ",
          " export const CONFIG = {",
          "*** Modify File: src/hooks/useSession.ts",
          " import { useEffect, useState } from 'react';",
          "+import { formatRelative } from '../utils/dateFormat';",
          " ",
          " export function useSession(id: string) {",
          "   const [session, setSession] = useState(null);",
          "+  const [lastActive, setLastActive] = useState('');",
        ].join("\n"),
      },
    },
    {
      key: "streaming-empty",
      label: "Streaming (no content yet)",
      status: "running",
      resultPatch: { success: undefined, content: undefined },
      argsPatch: { patch_text: undefined, streamContent: undefined },
    },
    {
      key: "failed",
      label: "Failed",
      status: "failed",
    },
  ],
};
