import type { ShortcutEntry } from "./types";

export const EDITOR_SHORTCUTS: ShortcutEntry[] = [
  {
    id: "save_file",
    command: "Save file",
    macKeys: "⌘S",
    winKeys: "Ctrl+S",
    scope: "editor",
    category: "file",
  },
  {
    id: "save_all",
    command: "Save all files",
    macKeys: "⇧⌘S",
    winKeys: "Ctrl+Shift+S",
    scope: "editor",
    category: "file",
  },
  {
    id: "close_file",
    command: "Close file",
    macKeys: "⌘W",
    winKeys: "Ctrl+W",
    scope: "editor",
    category: "file",
  },
  {
    id: "reload_file",
    command: "Reload file from disk",
    macKeys: "⇧⌘R",
    winKeys: "Ctrl+Shift+R",
    scope: "editor",
    category: "file",
  },
  {
    id: "go_to_line",
    command: "Go to line",
    macKeys: "⌃G",
    winKeys: "Ctrl+G",
    scope: "editor",
    category: "navigation",
  },
  {
    id: "go_to_definition",
    command: "Go to definition",
    macKeys: "F12",
    winKeys: "F12",
    scope: "editor",
    category: "navigation",
  },
  {
    id: "find_references",
    command: "Find all references",
    macKeys: "⇧F12",
    winKeys: "Shift+F12",
    scope: "editor",
    category: "navigation",
  },
  {
    id: "go_back",
    command: "Navigate back",
    macKeys: "⌘[",
    winKeys: "Ctrl+[",
    scope: "editor",
    category: "navigation",
  },
  {
    id: "go_forward",
    command: "Navigate forward",
    macKeys: "⌘]",
    winKeys: "Ctrl+]",
    scope: "editor",
    category: "navigation",
  },
  {
    id: "find",
    command: "Find in file",
    macKeys: "⌘F",
    winKeys: "Ctrl+F",
    scope: "editor",
    category: "search",
  },
  {
    id: "find_replace",
    command: "Find and replace",
    macKeys: "⌘H",
    winKeys: "Ctrl+H",
    scope: "editor",
    category: "search",
  },
  {
    id: "quick_open",
    command: "Quick open file",
    macKeys: "⌘P",
    winKeys: "Ctrl+P",
    scope: "editor",
    category: "search",
  },
  {
    id: "search_files",
    command: "Search in files",
    macKeys: "⇧⌘F",
    winKeys: "Ctrl+Shift+F",
    scope: "editor",
    category: "search",
  },
  {
    id: "go_to_symbol",
    command: "Go to symbol",
    macKeys: "⇧⌘O",
    winKeys: "Ctrl+Shift+O",
    scope: "editor",
    category: "search",
  },
  {
    id: "undo",
    command: "Undo",
    macKeys: "⌘Z",
    winKeys: "Ctrl+Z",
    scope: "editor",
    category: "editing",
  },
  {
    id: "redo",
    command: "Redo",
    macKeys: "⇧⌘Z",
    winKeys: "Ctrl+Shift+Z",
    scope: "editor",
    category: "editing",
  },
  {
    id: "format_document",
    command: "Format document",
    macKeys: "⇧⌥F",
    winKeys: "Shift+Alt+F",
    scope: "editor",
    category: "editing",
  },
  {
    id: "open_file_folder_tab",
    command: "Open File Folder tab",
    macKeys: "⌘G",
    winKeys: "Ctrl+G",
    scope: "editor",
    category: "view",
  },
  {
    id: "open_source_control_tab",
    command: "Open Source Control tab",
    macKeys: "⌘E",
    winKeys: "Ctrl+E",
    scope: "editor",
    category: "view",
  },
  {
    id: "open_terminal_tab",
    command: "Open Terminal tab",
    macKeys: "⌘J",
    winKeys: "Ctrl+J",
    scope: "editor",
    category: "view",
  },
  {
    id: "toggle_sidebar",
    command: "Toggle app sidebar",
    macKeys: "⌥⌘U",
    winKeys: "Ctrl+Alt+U",
    scope: "editor",
    category: "panels",
  },
  {
    id: "toggle_workstation_sidebar",
    command: "Toggle Workstation sidebar",
    macKeys: "⌘B",
    winKeys: "Ctrl+B",
    scope: "editor",
    category: "panels",
  },
  {
    id: "open_browser",
    command: "Open browser panel",
    macKeys: "⇧⌘B",
    winKeys: "Ctrl+Shift+B",
    scope: "editor",
    category: "view",
  },
  {
    id: "maximize_chat",
    command: "Focus Chat Panel / Show Workstation",
    macKeys: "⌥⌘B",
    winKeys: "Ctrl+Alt+B",
    scope: "editor",
    category: "view",
  },
  {
    id: "voice_input",
    command: "Toggle voice input in composer",
    macKeys: "⌃M",
    winKeys: "Ctrl+M",
    scope: "editor",
    category: "editing",
  },
];
