import type { ShortcutEntry } from "./types";

export const OVERLAY_SHORTCUTS: ShortcutEntry[] = [
  {
    id: "hunk_accept",
    command: "Accept hunk",
    macKeys: "⌘Y",
    winKeys: "Ctrl+Y",
    scope: "hunk-review",
    category: "editing",
  },
  {
    id: "hunk_reject",
    command: "Reject hunk",
    macKeys: "⌘N",
    winKeys: "Ctrl+N",
    scope: "hunk-review",
    category: "editing",
  },
  {
    id: "hunk_accept_all",
    command: "Accept all hunks",
    macKeys: "⇧⌘Y",
    winKeys: "Ctrl+Shift+Y",
    scope: "hunk-review",
    category: "editing",
  },
  {
    id: "hunk_reject_all",
    command: "Reject all hunks",
    macKeys: "⇧⌘N",
    winKeys: "Ctrl+Shift+N",
    scope: "hunk-review",
    category: "editing",
  },
  {
    id: "hunk_next",
    command: "Next hunk",
    macKeys: "J",
    winKeys: "J",
    scope: "hunk-review",
    category: "navigation",
  },
  {
    id: "hunk_previous",
    command: "Previous hunk",
    macKeys: "K",
    winKeys: "K",
    scope: "hunk-review",
    category: "navigation",
  },
  {
    id: "chat_send",
    command: "Send message",
    macKeys: "⌘ Enter",
    winKeys: "Ctrl+Enter",
    scope: "chat",
    category: "editing",
  },
  {
    id: "chat_newline",
    command: "New line",
    macKeys: "Enter",
    winKeys: "Enter",
    scope: "chat",
    category: "editing",
  },
  {
    id: "chat_mention",
    command: "Trigger mention",
    macKeys: "@",
    winKeys: "@",
    scope: "chat",
    category: "editing",
  },
  {
    id: "list_down",
    command: "Move down",
    macKeys: "↓",
    winKeys: "↓",
    scope: "list",
    category: "navigation",
  },
  {
    id: "list_up",
    command: "Move up",
    macKeys: "↑",
    winKeys: "↑",
    scope: "list",
    category: "navigation",
  },
  {
    id: "list_select",
    command: "Select item",
    macKeys: "Enter",
    winKeys: "Enter",
    scope: "list",
    category: "navigation",
  },
  {
    id: "list_close",
    command: "Close",
    macKeys: "Esc",
    winKeys: "Esc",
    scope: "list",
    category: "navigation",
  },
  {
    id: "menu_submenu",
    command: "Open submenu",
    macKeys: "→",
    winKeys: "→",
    scope: "context-menu",
    category: "navigation",
  },
  {
    id: "menu_back",
    command: "Close submenu",
    macKeys: "←",
    winKeys: "←",
    scope: "context-menu",
    category: "navigation",
  },
  {
    id: "modal_close",
    command: "Close modal",
    macKeys: "Esc",
    winKeys: "Esc",
    scope: "modal",
    category: "navigation",
  },
  {
    id: "modal_confirm",
    command: "Confirm",
    macKeys: "Enter",
    winKeys: "Enter",
    scope: "modal",
    category: "editing",
  },
];
