//! Hidden agent plumbing tool entries (not shown in user settings, but
//! still routed through the builtin metadata table for icon / chat-block
//! dispatch).

use super::aliases::*;
use super::macros::action_sub;

pub(super) static TOOLS: &[ToolEntry] = &[
    ToolEntry {
        name: tool_names::ASK_USER_QUESTIONS,
        description: "Ask the user structured questions during execution.",
        description_detail: "Presents structured prompts, confirmations, or multi-step choices mid-run and returns answers from the user to unblock the agent.",
        category: tool_categories::AGENT,
        icon_id: "message-circle-question-mark",
        simulator_app: AppChannels,
        app_subtool: OtherInteractions,
        chat_block: CbFallback,
        hidden: true,
        status_icons: &[("answered", "check-circle-2")],
        label_running: "tools.askUserQuestionsRunning",
        label_done: "tools.askUserQuestionsDone",
        label_failed: "tools.askUserQuestionsFailed",
        status_labels: &[
            ("answered", "tools.askUserQuestionsAnswered"),
            ("skipped", "tools.askUserQuestionsSkipped"),
        ],
        actions: &[
            action_sub!("ask", "Present a structured question and wait for user response", OtherInteractions, labels: "tools.askUserQuestionsAskRunning", "tools.askUserQuestionsAskDone", "tools.askUserQuestionsAskFailed"),
        ],
        required_capability: CapOrch,
        ..DEFAULT_TOOL_ENTRY
    },
    ToolEntry {
        name: tool_names::MANAGE_SESSION,
        description: "Manage agent sessions: create, monitor, and intervene.",
        description_detail: "Full lifecycle management for agent sessions.",
        category: tool_categories::AGENT,
        icon_id: "box",
        simulator_app: AppBackgroundTasks,
        app_subtool: SubSubagent,
        chat_block: CbSubagent,
        human_tool_key: Some(Sessions),
        hidden: true,
        label_running: "tools.askUserRunning",
        label_done: "tools.askUserDone",
        label_failed: "tools.askUserFailed",
        actions: &[
            action_sub!("create", "Start a new session with a task description", SubSubagent, labels: "tools.manageSessionCreateRunning", "tools.manageSessionCreateDone", "tools.manageSessionCreateFailed"),
            action_sub!("list", "Enumerate all sessions", SubSubagent, labels: "tools.manageSessionListRunning", "tools.manageSessionListDone", "tools.manageSessionListFailed"),
            action_sub!("get_status", "Detailed state including pending questions", SubSubagent, labels: "tools.manageSessionGetStatusRunning", "tools.manageSessionGetStatusDone", "tools.manageSessionGetStatusFailed"),
            action_sub!("send_message", "Send a message to a running session", SubSubagent, labels: "tools.manageSessionSendMessageRunning", "tools.manageSessionSendMessageDone", "tools.manageSessionSendMessageFailed"),
            action_sub!("answer_question", "Answer a pending question from the agent", SubSubagent, labels: "tools.manageSessionAnswerQuestionRunning", "tools.manageSessionAnswerQuestionDone", "tools.manageSessionAnswerQuestionFailed"),
            action_sub!("pause", "Pause a running session", SubSubagent, labels: "tools.manageSessionPauseRunning", "tools.manageSessionPauseDone", "tools.manageSessionPauseFailed"),
            action_sub!("resume", "Resume a paused session", SubSubagent, labels: "tools.manageSessionResumeRunning", "tools.manageSessionResumeDone", "tools.manageSessionResumeFailed"),
            action_sub!("cancel", "Cancel a session", SubSubagent, labels: "tools.manageSessionCancelRunning", "tools.manageSessionCancelDone", "tools.manageSessionCancelFailed"),
            action_sub!("open", "Navigate to the session in the IDE", SubSubagent, labels: "tools.manageSessionOpenRunning", "tools.manageSessionOpenDone", "tools.manageSessionOpenFailed"),
            action_sub!("upload_file", "Upload a file to the session worktree", SubSubagent, labels: "tools.manageSessionUploadFileRunning", "tools.manageSessionUploadFileDone", "tools.manageSessionUploadFileFailed"),
            action_sub!("merge", "Merge the worktree branch back to base", SubSubagent, labels: "tools.manageSessionMergeRunning", "tools.manageSessionMergeDone", "tools.manageSessionMergeFailed"),
        ],
        required_capability: CapManagement,
        ..DEFAULT_TOOL_ENTRY
    },
    ToolEntry {
        name: tool_names::SEND_MESSAGE,
        description: "Send messages to channels (Telegram, Discord, etc.).",
        description_detail: "Posts outbound messages through configured channels such as Telegram or Discord using stored credentials and channel routing.",
        category: tool_categories::AGENT,
        icon_id: "send",
        simulator_app: AppChannels,
        app_subtool: Message,
        chat_block: CbSentMessage,
        hidden: true,
        label_running: "tools.messageRunning",
        label_done: "tools.messageDone",
        label_failed: "tools.messageFailed",
        actions: &[
            action_sub!("send", "Send a message to a configured channel", Message, labels: "tools.messageSendRunning", "tools.messageSendDone", "tools.messageSendFailed"),
        ],
        required_capability: CapGateway,
        ..DEFAULT_TOOL_ENTRY
    },
    ToolEntry {
        name: tool_names::SEND_TO_INBOX,
        description: "Send a notification or summary to the user's inbox.",
        description_detail: "Delivers messages, task results, periodic reports, or reminders to the user's local inbox for later review.",
        category: tool_categories::AGENT,
        icon_id: "inbox",
        simulator_app: AppChannels,
        app_subtool: Message,
        chat_block: CbSentMessage,
        hidden: true,
        label_running: "tools.sendToInboxRunning",
        label_done: "tools.sendToInboxDone",
        label_failed: "tools.sendToInboxFailed",
        required_capability: CapOrch,
        ..DEFAULT_TOOL_ENTRY
    },
    ToolEntry {
        name: tool_names::TOOL_SEARCH,
        description: "Discover additional tools not currently loaded.",
        description_detail: "Searches across deferred (on-demand) tools by keyword and returns matching names and descriptions. Enables a two-tier tool loading strategy where specialized tools stay dormant until the agent explicitly discovers them.",
        category: tool_categories::AGENT,
        icon_id: "search",
        simulator_app: AppCode,
        app_subtool: OtherTool,
        chat_block: CbTitleOnly,
        hidden: true,
        label_running: "tools.toolSearchRunning",
        label_done: "tools.toolSearchDone",
        label_failed: "tools.toolSearchFailed",
        required_capability: CapOrch,
        ..DEFAULT_TOOL_ENTRY
    },
    ToolEntry {
        name: tool_names::SUGGEST_NEXT_STEPS,
        description: "Propose contextual next steps at end of turn.",
        description_detail: "Agent suggests 2-3 actionable next steps as clickable cards. The user picks one to continue the conversation.",
        category: tool_categories::ORCHESTRATION,
        icon_id: "arrow-big-right-dash",
        simulator_app: AppChannels,
        app_subtool: OtherInteractions,
        chat_block: CbTitleOnly,
        hidden: true,
        label_running: "tools.suggestNextStepsRunning",
        label_done: "tools.suggestNextStepsDone",
        label_failed: "tools.suggestNextStepsFailed",
        required_capability: CapOrch,
        ..DEFAULT_TOOL_ENTRY
    },
    ToolEntry {
        name: tool_names::ORG_SEND_MESSAGE,
        description: "Send a typed org message inside an Agent Org run.",
        description_detail: "Org messaging primitive: routes a typed AgentMessage (plain or structured RPC) to an org participant by name, agent_id, or broadcast. Persisted to the org inbox; surfaced to the recipient on its next turn.",
        category: tool_categories::ORCHESTRATION,
        icon_id: "mail",
        simulator_app: AppChannels,
        app_subtool: Message,
        chat_block: CbSentMessage,
        hidden: true,
        label_running: "tools.orgSendMessageRunning",
        label_done: "tools.orgSendMessageDone",
        label_failed: "tools.orgSendMessageFailed",
        required_capability: CapOrch,
        ..DEFAULT_TOOL_ENTRY
    },
];
