//! Desktop automation tool entries.

use super::aliases::*;
use super::macros::action_sub;

pub(super) static TOOLS: &[ToolEntry] = &[ToolEntry {
    name: tool_names::CONTROL_DESKTOP_WITH_PEEKABOO,
    description: "Run raw macOS desktop automation commands through the bundled Peekaboo CLI.",
    description_detail: "Executes the selected subcommand with ORGII's bundled Peekaboo binary. Use for see, image, app, open, click, type, paste, press, hotkey, scroll, drag, window, menu, menubar, dock, dialog, space, permissions, and other supported Peekaboo commands.",
    category: tool_categories::DESKTOP,
    icon_id: "monitor",
    simulator_app: AppBrowser,
    app_subtool: SubBrowser,
    chat_block: CbFallback,
    action_icons: &[
        ("see", "fullscreen"),
        ("image", "camera"),
        ("list", "list"),
        ("permissions", "shield-check"),
        ("app", "monitor"),
        ("open", "globe"),
        ("click", "mouse-pointer-2"),
        ("move", "mouse-pointer-2"),
        ("drag", "mouse-pointer-2"),
        ("swipe", "mouse-pointer-2"),
        ("type", "keyboard"),
        ("paste", "clipboard-list"),
        ("press", "keyboard"),
        ("hotkey", "keyboard"),
        ("scroll", "mouse-pointer-2"),
        ("set-value", "file-pen-line"),
        ("perform-action", "activity"),
        ("window", "monitor"),
        ("menu", "list"),
        ("menubar", "list"),
        ("dock", "monitor"),
        ("dialog", "messages-square"),
        ("space", "layers"),
        ("clipboard", "clipboard-list"),
    ],
    label_running: "tools.desktopRunning",
    label_done: "tools.desktopDone",
    label_failed: "tools.desktopFailed",
    actions: &[
        action_sub!("see", "Capture and map UI elements with Peekaboo", SubBrowser, labels: "tools.desktopSeeRunning", "tools.desktopSeeDone", "tools.desktopSeeFailed"),
        action_sub!("image", "Capture a screen, window, app, or menu image with Peekaboo", SubBrowser, labels: "tools.desktopImageRunning", "tools.desktopImageDone", "tools.desktopImageFailed"),
        action_sub!("list", "List apps, windows for an app, screens, menubar, or permissions with Peekaboo", SubBrowser, labels: "tools.desktopListRunning", "tools.desktopListDone", "tools.desktopListFailed"),
        action_sub!("permissions", "Check macOS desktop permissions with Peekaboo", SubBrowser, labels: "tools.desktopPermissionsRunning", "tools.desktopPermissionsDone", "tools.desktopPermissionsFailed"),
        action_sub!("app", "Launch, switch, hide, unhide, quit, or relaunch apps with Peekaboo", SubBrowser, labels: "tools.desktopAppRunning", "tools.desktopAppDone", "tools.desktopAppFailed"),
        action_sub!("open", "Open a URL or file with Peekaboo", SubBrowser, labels: "tools.desktopOpenRunning", "tools.desktopOpenDone", "tools.desktopOpenFailed"),
        action_sub!("click", "Click an element, label, or coordinate with Peekaboo", SubBrowser, labels: "tools.desktopClickRunning", "tools.desktopClickDone", "tools.desktopClickFailed"),
        action_sub!("move", "Move the mouse cursor with Peekaboo", SubBrowser, labels: "tools.desktopMoveRunning", "tools.desktopMoveDone", "tools.desktopMoveFailed"),
        action_sub!("drag", "Perform a drag-and-drop operation with Peekaboo", SubBrowser, labels: "tools.desktopDragRunning", "tools.desktopDragDone", "tools.desktopDragFailed"),
        action_sub!("swipe", "Perform a swipe gesture with Peekaboo", SubBrowser, labels: "tools.desktopSwipeRunning", "tools.desktopSwipeDone", "tools.desktopSwipeFailed"),
        action_sub!("type", "Enter text or keyboard input with Peekaboo", SubBrowser, labels: "tools.desktopTypeRunning", "tools.desktopTypeDone", "tools.desktopTypeFailed"),
        action_sub!("paste", "Paste text or clipboard content with Peekaboo", SubBrowser, labels: "tools.desktopPasteRunning", "tools.desktopPasteDone", "tools.desktopPasteFailed"),
        action_sub!("press", "Press individual keys with Peekaboo", SubBrowser, labels: "tools.desktopPressRunning", "tools.desktopPressDone", "tools.desktopPressFailed"),
        action_sub!("hotkey", "Press a modifier key combination with Peekaboo", SubBrowser, labels: "tools.desktopHotkeyRunning", "tools.desktopHotkeyDone", "tools.desktopHotkeyFailed"),
        action_sub!("scroll", "Scroll the mouse wheel with Peekaboo", SubBrowser, labels: "tools.desktopScrollRunning", "tools.desktopScrollDone", "tools.desktopScrollFailed"),
        action_sub!("set-value", "Set an accessibility element value with Peekaboo", SubBrowser, labels: "tools.desktopSetValueRunning", "tools.desktopSetValueDone", "tools.desktopSetValueFailed"),
        action_sub!("perform-action", "Perform a named accessibility action with Peekaboo", SubBrowser, labels: "tools.desktopPerformActionRunning", "tools.desktopPerformActionDone", "tools.desktopPerformActionFailed"),
        action_sub!("window", "Manipulate application windows with Peekaboo", SubBrowser, labels: "tools.desktopWindowRunning", "tools.desktopWindowDone", "tools.desktopWindowFailed"),
        action_sub!("menu", "Interact with app menus with Peekaboo", SubBrowser, labels: "tools.desktopMenuRunning", "tools.desktopMenuDone", "tools.desktopMenuFailed"),
        action_sub!("menubar", "Interact with macOS menubar items with Peekaboo", SubBrowser, labels: "tools.desktopMenubarRunning", "tools.desktopMenubarDone", "tools.desktopMenubarFailed"),
        action_sub!("dock", "Interact with the macOS Dock with Peekaboo", SubBrowser, labels: "tools.desktopDockRunning", "tools.desktopDockDone", "tools.desktopDockFailed"),
        action_sub!("dialog", "Interact with system dialogs and alerts with Peekaboo", SubBrowser, labels: "tools.desktopDialogRunning", "tools.desktopDialogDone", "tools.desktopDialogFailed"),
        action_sub!("space", "Manage macOS Spaces with Peekaboo", SubBrowser, labels: "tools.desktopSpaceRunning", "tools.desktopSpaceDone", "tools.desktopSpaceFailed"),
        action_sub!("clipboard", "Read or write the macOS clipboard with Peekaboo", SubBrowser, labels: "tools.desktopClipboardRunning", "tools.desktopClipboardDone", "tools.desktopClipboardFailed"),
    ],
    required_capability: CapDesktop,
    ..DEFAULT_TOOL_ENTRY
}];
