//! Skill synchronization for CLI agents.
//!
//! CLI agents (Cursor, Claude Code, Codex, Gemini, Kiro, Copilot) are external
//! subprocesses — we cannot control their system prompts. Each agent has its own
//! native rules system that automatically loads project-level instruction files:
//!
//! | Agent       | Rules file                              |
//! |-------------|-----------------------------------------|
//! | Cursor CLI  | `.cursor/rules/*.mdc` (alwaysApply)     |
//! | Claude Code | `.claude/rules/*.md`                    |
//! | Codex       | `AGENTS.md` (walks up from cwd)         |
//! | Gemini CLI  | `GEMINI.md` (walks up from cwd)         |
//! | Copilot     | reads `CLAUDE.md`, `AGENTS.md`, etc.    |
//! | Kiro        | no known rules file                     |
//!
//! This module writes orgii-managed skill files into each agent's native rules
//! location before the CLI subprocess is spawned, then cleans them up after
//! the session completes.

use std::fs;
use std::path::{Path, PathBuf};

use agent_core::skills::loader::{global_skills_dir, SkillInfo, SkillsLoader};
use key_vault::key_store::ModelType;

/// Marker header embedded in every generated file so we can identify our own files.
const ORGII_MARKER: &str = "<!-- generated by orgii — do not edit manually -->";

/// Sync skills into the CLI agent's native rules files.
///
/// Returns the list of file paths that were written, for cleanup after the
/// session completes. Files are named with a `orgii-` prefix to avoid
/// colliding with user-owned rule files.
///
/// If `skills_enabled` is false or no skills are found, no files are written.
pub fn sync_skills_for_agent(
    agent: &ModelType,
    workspace_path: &Path,
    skills_enabled: bool,
    disabled_skills: &[String],
) -> Vec<PathBuf> {
    if !skills_enabled {
        return Vec::new();
    }

    let loader = SkillsLoader::new(&workspace_path.join(".orgii"))
        .with_builtin_dir(global_skills_dir())
        .with_disabled_skills(disabled_skills.to_vec());

    let all_skills: Vec<SkillInfo> = loader
        .list_skills()
        .into_iter()
        .filter(|skill| skill.enabled)
        .collect();

    if all_skills.is_empty() {
        return Vec::new();
    }

    let content = build_skills_content(&loader, &all_skills, disabled_skills);

    let targets = rule_targets_for_agent(agent, workspace_path);
    let mut written: Vec<PathBuf> = Vec::new();

    for target in targets {
        match write_rule_file(&target, &content) {
            Ok(()) => {
                tracing::info!(
                    "[skill_sync] Wrote {} skill(s) to {}",
                    all_skills.len(),
                    target.display()
                );
                written.push(target);
            }
            Err(err) => {
                tracing::warn!("[skill_sync] Failed to write {}: {}", target.display(), err);
            }
        }
    }

    written
}

/// Remove files that were created by `sync_skills_for_agent`.
pub fn cleanup_synced_skill_files(paths: &[PathBuf]) {
    for path in paths {
        if !path.exists() {
            continue;
        }
        // Safety check: only delete files containing our marker
        let is_ours = fs::read_to_string(path)
            .map(|content| content.contains(ORGII_MARKER))
            .unwrap_or(false);
        if !is_ours {
            tracing::warn!(
                "[skill_sync] Skipping cleanup of {} — missing orgii marker",
                path.display()
            );
            continue;
        }
        if let Err(err) = fs::remove_file(path) {
            tracing::warn!(
                "[skill_sync] Failed to clean up {}: {}",
                path.display(),
                err
            );
        }
    }
}

/// Determine the rule file path(s) to write for a given agent.
fn rule_targets_for_agent(agent: &ModelType, workspace_path: &Path) -> Vec<PathBuf> {
    match agent {
        ModelType::CursorCli => {
            vec![workspace_path
                .join(".cursor")
                .join("rules")
                .join("orgii-skills.mdc")]
        }
        ModelType::ClaudeCode => {
            vec![workspace_path
                .join(".claude")
                .join("rules")
                .join("orgii-skills.md")]
        }
        ModelType::Codex => {
            // Codex walks up from cwd looking for AGENTS.md; we write a separate
            // file and rely on Codex picking up all .md files in the workspace root.
            // Use .codex/AGENTS.md which Codex also discovers.
            vec![workspace_path.join(".codex").join("orgii-skills.md")]
        }
        ModelType::GeminiCli => {
            vec![workspace_path.join(".gemini").join("orgii-skills.md")]
        }
        ModelType::Copilot => {
            // Copilot reads CLAUDE.md, AGENTS.md, and GEMINI.md.
            // Write to .github/instructions/ which Copilot explicitly supports.
            vec![workspace_path
                .join(".github")
                .join("instructions")
                .join("orgii-skills.instructions.md")]
        }
        ModelType::Kiro => {
            // Kiro has no known rules file system — skills are injected into
            // the user prompt instead (handled separately in runner.rs).
            Vec::new()
        }
        // API key providers are not CLI agents
        _ => Vec::new(),
    }
}

/// Build the user prompt snippet for agents without a rules file (Kiro).
///
/// Returns `None` if skills are disabled or no skills found.
pub fn build_skills_prompt_injection(
    workspace_path: &Path,
    skills_enabled: bool,
    disabled_skills: &[String],
) -> Option<String> {
    if !skills_enabled {
        return None;
    }

    let loader = SkillsLoader::new(&workspace_path.join(".orgii"))
        .with_builtin_dir(global_skills_dir())
        .with_disabled_skills(disabled_skills.to_vec());

    let all_skills: Vec<SkillInfo> = loader
        .list_skills()
        .into_iter()
        .filter(|skill| skill.enabled)
        .collect();

    if all_skills.is_empty() {
        return None;
    }

    let content = build_skills_content(&loader, &all_skills, disabled_skills);
    Some(format!("<skills>\n{}\n</skills>", content))
}

// ==========================================================================
// Private helpers
// ==========================================================================

/// Build the formatted skills content shared by all agents.
fn build_skills_content(
    loader: &SkillsLoader,
    skills: &[SkillInfo],
    disabled_skills: &[String],
) -> String {
    let mut parts: Vec<String> = Vec::new();

    let always_sections = loader.build_always_skills_manifest_section(disabled_skills, None);
    parts.extend(always_sections);

    // Summary of all available skills with scan instructions
    let summary_lines: Vec<String> = skills
        .iter()
        .map(|skill| {
            let status = if skill.available {
                "available"
            } else {
                "unavailable"
            };
            let desc = if skill.description.is_empty() {
                "No description".to_string()
            } else {
                skill.description.clone()
            };
            format!(
                "- **{}** ({}): {} [{}]\n  Path: `{}`",
                skill.name,
                skill.source,
                desc,
                status,
                skill.path.display()
            )
        })
        .collect();

    parts.push(format!(
        "## Skills (mandatory)\n\n\
         Before replying: scan the skill descriptions below.\n\
         - If exactly one skill clearly applies: read its SKILL.md using read_file, then follow it.\n\
         - If multiple could apply: choose the most specific one, then read/follow it.\n\
         - If none clearly apply: do not read any SKILL.md.\n\
         Constraints: never read more than one skill up front; only read after selecting.\n\n\
         {}",
        summary_lines.join("\n")
    ));

    parts.join("\n\n---\n\n")
}

/// Write a rule file with the appropriate wrapper for its format.
fn write_rule_file(target: &Path, content: &str) -> Result<(), String> {
    // Ensure parent directory exists
    if let Some(parent) = target.parent() {
        if !parent.exists() {
            fs::create_dir_all(parent).map_err(|err| {
                format!("Failed to create directory {}: {}", parent.display(), err)
            })?;
        }
    }

    let ext = target.extension().and_then(|e| e.to_str()).unwrap_or("");
    let wrapped = match ext {
        "mdc" => format_mdc(content),
        _ => format_markdown(content),
    };

    fs::write(target, wrapped)
        .map_err(|err| format!("Failed to write {}: {}", target.display(), err))
}

/// Wrap content as a Cursor `.mdc` file with `alwaysApply: true` frontmatter.
fn format_mdc(content: &str) -> String {
    format!(
        "---\ndescription: Skills injected by orgii for coding sessions\nalwaysApply: true\n---\n\n{marker}\n\n{content}",
        marker = ORGII_MARKER,
        content = content,
    )
}

/// Wrap content as a plain markdown file with the orgii marker.
fn format_markdown(content: &str) -> String {
    format!(
        "{marker}\n\n{content}",
        marker = ORGII_MARKER,
        content = content,
    )
}

// ==========================================================================
// Convention sync (replaces sync_conventions_to_cursorrules)
// ==========================================================================

/// Sync project conventions (`.orgii/agent-rules.md`) to each CLI agent's
/// native rules file.
///
/// Replaces the old `sync_conventions_to_cursorrules()` which wrote to the
/// deprecated `.cursorrules` file (which Cursor agent mode ignores).
pub fn sync_conventions_for_agent(agent: &ModelType, workspace_path: &Path) -> Vec<PathBuf> {
    let conventions_path = workspace_path.join(".orgii").join("agent-rules.md");
    let content = match fs::read_to_string(&conventions_path) {
        Ok(content) if !content.trim().is_empty() => content,
        _ => return Vec::new(),
    };

    let targets = convention_targets_for_agent(agent, workspace_path);
    let mut written: Vec<PathBuf> = Vec::new();

    for target in targets {
        // Skip if a non-orgii file already exists at this path
        if target.exists() {
            let is_ours = fs::read_to_string(&target)
                .map(|existing| existing.contains(ORGII_MARKER))
                .unwrap_or(false);
            if !is_ours {
                continue;
            }
        }

        match write_rule_file(&target, &content) {
            Ok(()) => {
                tracing::info!("[skill_sync] Synced conventions to {}", target.display());
                written.push(target);
            }
            Err(err) => {
                tracing::warn!(
                    "[skill_sync] Failed to sync conventions to {}: {}",
                    target.display(),
                    err
                );
            }
        }
    }

    written
}

/// Determine convention file paths for each agent type.
fn convention_targets_for_agent(agent: &ModelType, workspace_path: &Path) -> Vec<PathBuf> {
    match agent {
        ModelType::CursorCli => {
            vec![workspace_path
                .join(".cursor")
                .join("rules")
                .join("orgii-conventions.mdc")]
        }
        ModelType::ClaudeCode => {
            vec![workspace_path
                .join(".claude")
                .join("rules")
                .join("orgii-conventions.md")]
        }
        ModelType::Codex => {
            vec![workspace_path.join(".codex").join("orgii-conventions.md")]
        }
        ModelType::GeminiCli => {
            vec![workspace_path.join(".gemini").join("orgii-conventions.md")]
        }
        ModelType::Copilot => {
            vec![workspace_path
                .join(".github")
                .join("instructions")
                .join("orgii-conventions.instructions.md")]
        }
        ModelType::Kiro => Vec::new(),
        _ => Vec::new(),
    }
}
