/**
 * Icon Name Mapping
 *
 * Maps icon names (lowercase-hyphen format) to Lucide icon components
 * This file has no dependencies to avoid circular imports
 */
import {
  Infinity as InfinityIcon,
  Activity,
  Airplay,
  BadgeCent,
  BarChart,
  BarChart3,
  Blocks,
  BookMarked,
  BookOpen,
  Bot,
  Box,
  ChartGantt,
  ChartNoAxesGantt,
  ChevronsLeftRightEllipsis,
  CircleDollarSign,
  CirclePile,
  Code,
  Coins,
  Command,
  Compass,
  Database,
  Diff,
  Folder,
  FolderCode,
  FolderKanban,
  Fuel,
  Globe,
  History,
  Home,
  IdCard,
  Inbox,
  KeyRound,
  LayoutList,
  Lightbulb,
  ListTodo,
  MapPin,
  MessageSquare,
  Network,
  PackageCheck,
  Play,
  PlayCircle,
  Plug,
  Plus,
  Radar,
  Rocket,
  Search,
  SearchCode,
  Server,
  Settings,
  Sparkles,
  Store,
  Terminal,
  Ticket,
  Users,
  Wallet,
  Wand2,
  Workflow,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

/**
 * Maps icon names to their corresponding Lucide components
 * Useful for dynamic icon rendering
 */
export const ICON_NAME_MAP: Record<string, LucideIcon | null> = {
  folder: Folder,
  "message-square": MessageSquare,
  code: Code,
  "folder-code": FolderCode,
  terminal: Terminal,
  globe: Globe,
  "file-text": BookOpen,
  "book-open": BookOpen,
  "book-marked": BookMarked,
  bot: Bot,
  plus: Plus,
  "plus-circle": Plus,
  play: Play,
  "play-circle": PlayCircle,
  settings: Settings,
  cog: Settings,
  bolt: Settings,
  "bar-chart": BarChart,
  "bar-chart-3": BarChart3,
  server: Server,
  command: Command,
  compass: Compass,
  search: Search,
  "search-code": SearchCode,
  "chart-gantt": ChartGantt,
  box: Box,
  coins: Coins,
  database: Database,
  "git-compare-arrows": Diff,
  diff: Diff,
  history: History,
  lightbulb: Lightbulb,
  sparkles: Sparkles,
  ticket: Ticket,
  "key-round": KeyRound,
  "id-card": IdCard,
  infinity: InfinityIcon,
  "layout-list": LayoutList,
  "list-todo": ListTodo,
  "folder-kanban": FolderKanban,
  radar: Radar,
  "chart-no-axes-gantt": ChartNoAxesGantt,
  activity: Activity,
  users: Users,
  kanban: ChartGantt, // Using ChartGantt for kanban
  home: Home,
  inbox: Inbox,
  wallet: Wallet,
  "badge-cent": BadgeCent,
  "circle-dollar-sign": CircleDollarSign,
  blocks: Blocks,
  "package-check": PackageCheck,
  plug: Plug,
  rocket: Rocket,
  "chevrons-left-right-ellipsis": ChevronsLeftRightEllipsis,
  store: Store,
  fuel: Fuel,
  workflow: Workflow,
  "map-pin": MapPin,
  network: Network,
  airplay: Airplay,
  "circle-pile": CirclePile,
  "wand-2": Wand2,
};

/**
 * Get Lucide icon component by name
 */
export function getIconByName(iconName: string): LucideIcon | null {
  return ICON_NAME_MAP[iconName] ?? null;
}
