export const WORKSPACE_DEFAULT_REPO_LOCATION = {
  DOCUMENTS_GITHUB: "documents-github",
  DOCUMENTS_ORGII: "documents-orgii",
  DOCUMENTS: "documents",
  CUSTOM: "custom",
} as const;

export const WORKSPACE_DEFAULT_REPO_LOCATION_VALUES = [
  WORKSPACE_DEFAULT_REPO_LOCATION.DOCUMENTS_GITHUB,
  WORKSPACE_DEFAULT_REPO_LOCATION.DOCUMENTS_ORGII,
  WORKSPACE_DEFAULT_REPO_LOCATION.DOCUMENTS,
  WORKSPACE_DEFAULT_REPO_LOCATION.CUSTOM,
] as const;

export type WorkspaceDefaultRepoLocation =
  (typeof WORKSPACE_DEFAULT_REPO_LOCATION_VALUES)[number];
