//! Strongly-typed identifier newtypes.
//!
//! Every ID flowing through the relay is wrapped so that we can never mix
//! up a [`DeviceId`] (a phone) with a [`DesktopId`] (a workstation) at the
//! type level — even though both serialize as opaque strings on the wire.

use serde::{Deserialize, Serialize};
use std::fmt;

macro_rules! string_newtype {
    ($(#[$meta:meta])* $name:ident) => {
        $(#[$meta])*
        #[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
        #[serde(transparent)]
        pub struct $name(pub String);

        impl $name {
            pub fn new(s: impl Into<String>) -> Self {
                Self(s.into())
            }

            pub fn as_str(&self) -> &str {
                &self.0
            }
        }

        impl fmt::Display for $name {
            fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
                f.write_str(&self.0)
            }
        }

        impl From<String> for $name {
            fn from(s: String) -> Self {
                Self(s)
            }
        }

        impl From<&str> for $name {
            fn from(s: &str) -> Self {
                Self(s.to_owned())
            }
        }
    };
}

string_newtype! {
    /// Identifies a ORGII account / tenant on the relay. One UserHub actor per
    /// `UserId` holds all paired devices and desktops for that account.
    UserId
}

string_newtype! {
    /// Identifies a single desktop instance running the ORGII app. A user may
    /// have multiple — home Mac, office Linux, laptop. Every RPC frame must
    /// carry the `DesktopId` it targets so the relay routes correctly.
    DesktopId
}

string_newtype! {
    /// Identifies a single mobile / browser device paired with one or more
    /// desktops. Tokens are scoped per-`DeviceId` for precise revocation.
    DeviceId
}

string_newtype! {
    /// Correlates an RPC call with its result. Generated by the caller and
    /// must be unique within the WebSocket connection's lifetime.
    RpcId
}
